export const fleetMachinesData = [
    {
        id: 1,
        name: "CAT 320D Excavator",
        serialNumber: "CAT320D001",
        image: "/images/visionlink/Image1.jpg",
        status: "operational",
        alerts: 0,
        location: "Johannesburg Mining Site A",
        lastComm: "2 min ago",
        healthScore: 92,
        utilization: 87,
        fuel: 78,
        hours: "2,456h",
        operator: "John Smith",
        coordinates: { lat: -26.2041, lng: 28.0473 }
    },
    {
        id: 2,
        name: "CAT 950M Wheel Loader",
        serialNumber: "CAT950M002",
        image: "/images/visionlink/Image2.jpg",
        status: "warning",
        alerts: 2,
        warningCount: 1,
        alertCount: 2,
        location: "Cape Town Construction Site B",
        lastComm: "5 min ago",
        healthScore: 76,
        utilization: 65,
        fuel: 45,
        hours: "3,120h",
        operator: "Mike Johnson",
        coordinates: { lat: -33.9249, lng: 18.4241 }
    },
    {
        id: 3,
        name: "CAT 725C Articulated Truck",
        serialNumber: "CAT725C003",
        image: "/images/visionlink/Image1.jpg",
        status: "critical",
        alerts: 3,
        alertCount: 3,
        location: "Durban Port Operations C",
        lastComm: "1 hour ago",
        healthScore: 45,
        utilization: 0,
        fuel: 90,
        hours: "4,785h",
        operator: "Sarah Williams",
        coordinates: { lat: -29.8587, lng: 31.0218 }
    },
    {
        id: 4,
        name: "CAT D6 Bulldozer",
        serialNumber: "CATD6004",
        image: "/images/visionlink/Image2.jpg",
        status: "maintenance",
        alerts: 0,
        location: "Pretoria Infrastructure Site D",
        lastComm: "15 min ago",
        healthScore: 68,
        utilization: 0,
        fuel: 100,
        hours: "5,234h",
        operator: "David Brown",
        coordinates: { lat: -25.7479, lng: 28.2293 }
    },
    {
        id: 5,
        name: "CAT 140M Motor Grader",
        serialNumber: "CAT140M005",
        image: "/images/visionlink/Image1.jpg",
        status: "operational",
        alerts: 0,
        location: "Bloemfontein Road Project E",
        lastComm: "3 min ago",
        healthScore: 88,
        utilization: 72,
        fuel: 82,
        hours: "1,987h",
        operator: "Emma Davis",
        coordinates: { lat: -29.1211, lng: 26.2142 }
    },
    {
        id: 6,
        name: "CAT 730 Articulated Truck",
        serialNumber: "CAT730006",
        image: "/images/visionlink/Image2.jpg",
        status: "offline",
        alerts: 0,
        location: "Port Elizabeth Warehouse F",
        lastComm: "2 hours ago",
        healthScore: 0,
        utilization: 0,
        fuel: 0,
        hours: "6,543h",
        operator: "Not assigned",
        coordinates: { lat: -33.9608, lng: 25.6022 }
    }
];

export const fleetStatusSummary = {
    operational: 2,
    warning: 1,
    critical: 1,
    maintenance: 1,
    offline: 1
};